name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "20.18.0"  # version de Node.js

permissions:
  contents: write
  packages: write

# Définition d'une configuration commune pour les jobs
common-job: &common-job
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

# All JOBS------------------------------------------------------------
jobs:
  install:
    <<: *common-job  # Hérite de la configuration commune
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install && npm ci --cache .npm --prefer-offline
      - name: Verify ESLint installation
        run: npm list eslint

  unit-test:
    <<: *common-job  # Hérite de la configuration commune
    needs: install
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test

  integration-test:
    <<: *common-job  # Hérite de la configuration commune
    needs: unit-test
    steps:
      - name: Run integration tests
        run: echo "Hello Integration !"

  e2e-test:
    <<: *common-job  # Hérite de la configuration commune
    needs: integration-test
    steps:
      - name: Run end-to-end tests
        run: echo "Hello E2E !"
